import type { Metadata } from "next";
import Image from "next/image";

import Nav from "@/components/nav";
import { ThemeProvider } from "@/components/theme-provider";
import "@/styles/globals.css";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Boireader",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="hidden md:flex flex-col relative overflow-x-hidden">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Nav />
          <div>{children}</div>
          <Footer />
        </ThemeProvider>
      </body>
      {/* <div className="flex flex-col gap-y-10 md:hidden px-14 justify-center items-center w-screen h-screen">
        <Image src="/logo.png" width={200} height={200} alt="logo" />

        <p className="font-bold text-xl tracking-wider text-transparent bg-clip-text bg-gradient-to-tr from-red-500 to-yellow-500">
          Apologies, our website isn&apos;t fully mobile-friendly yet. For the
          best experience, try it on desktop or laptop.
        </p>
      </div> */}
    </html>
  );
}
