import Nav from "@/components/nav";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Boireader",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative h-max w-screen overflow-x-hidden">
        <Nav />
        <div className="w-full pt-24 h-max bg-none z-50">{children}</div>
        {/* <Footer /> */}
        {/* <div className="w-screen h-screen absolute top-0 left-0 bg-pattern z-0" /> */}
      </body>
    </html>
  );
}
